name: Cypress Tests

on: push

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Start Server
        run: npm run serve &

      - name: Cypress E2E Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          start: npm run serve
          wait-on: 'http://localhost:8080'
          wait-on-timeout: 60

  cypress-component:
    runs-on: ubuntu-latest
    needs: cypress-e2e
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress Component Tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          command: npx cypress run-ct
